# Generated by Django 2.2 on 2019-04-18 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qcontain', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cchoose', models.CharField(max_length=20)),
                ('ccount', models.IntegerField(default=0)),
                ('cvalues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Questions')),
            ],
        ),
    ]
